#!/usr/bin/env node
/**
 * tokens/tokens.mjs -> CSS custom properties, Tailwind theme, TS types.
 *
 *   node packages/ui/scripts/build-theme.mjs
 *
 * Writes (all generated — change tokens.mjs or this script, never the output):
 *   src/styles/tokens.generated.css   `--a-*` custom properties, per theme
 *   src/styles/theme.generated.css    Tailwind v4 `@theme inline` mapping
 *   src/lib/tokens.generated.ts       token names + values for types and docs
 *
 * The Tailwind theme resets each namespace it owns (`--color-*: initial` …)
 * so the only colours, radii, shadows and type sizes a component can reach
 * are ours. Anyone adding a near-duplicate has to add it here, in review.
 */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { palette, scales, themes } from '../tokens/tokens.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const out = (p) => join(here, '..', p);
const HEADER = '/* GENERATED by scripts/build-theme.mjs from tokens/tokens.mjs. Do not edit. */\n';

const key = (k) => String(k).replace('.', '_'); // `0.5` -> `0_5`: dots are not valid in names

// ── palette ────────────────────────────────────────────────────────────────
const paletteVars = [];
for (const [name, value] of Object.entries(palette)) {
  if (typeof value === 'string') paletteVars.push([`--a-palette-${name}`, value]);
  else for (const [step, v] of Object.entries(value)) paletteVars.push([`--a-palette-${name}-${step}`, v]);
}
const paletteNames = new Set(paletteVars.map(([n]) => n));

/** `neutral.200` -> var(--a-palette-neutral-200); literals pass through. */
function resolveColor(value, where) {
  if (!/^[a-z]+(\.\d+)?$/.test(value)) return value;
  const name = `--a-palette-${value.replace('.', '-')}`;
  if (!paletteNames.has(name)) throw new Error(`${where}: unknown palette reference "${value}"`);
  return `var(${name})`;
}

// ── semantic colours must be defined identically across themes ────────────
const themeNames = Object.keys(themes);
const colorNames = Object.keys(themes.light);
for (const t of themeNames) {
  const missing = colorNames.filter((c) => !(c in themes[t]));
  const extra = Object.keys(themes[t]).filter((c) => !colorNames.includes(c));
  if (missing.length || extra.length) {
    throw new Error(`theme "${t}" differs from light — missing: ${missing}; extra: ${extra}`);
  }
}

// ── contrast: fail the build on unreadable pairs ────────────────────────────
/** Resolve a theme value to an `oklch(...)` literal. */
function literal(theme, name) {
  const v = themes[theme][name];
  const m = /^([a-z]+)\.(\d+)$/.exec(v);
  return m ? palette[m[1]][m[2]] : palette[v] ?? v;
}
/** oklch(L C H) -> relative luminance (WCAG), via OKLab -> linear sRGB. */
function luminance(css) {
  const m = /oklch\(([\d.]+) ([\d.]+) ([\d.]+)/.exec(css);
  if (!m) return null; // translucent overlays etc. are not text pairs
  const [L, C, H] = m.slice(1).map(Number);
  const a = C * Math.cos((H * Math.PI) / 180);
  const b = C * Math.sin((H * Math.PI) / 180);
  const l = (L + 0.3963377774 * a + 0.2158037573 * b) ** 3;
  const mm = (L - 0.1055613458 * a - 0.0638541728 * b) ** 3;
  const s = (L - 0.0894841775 * a - 1.291485548 * b) ** 3;
  const clamp = (x) => Math.min(1, Math.max(0, x));
  const r = clamp(4.0767416621 * l - 3.3077115913 * mm + 0.2309699292 * s);
  const g = clamp(-1.2684380046 * l + 2.6097574011 * mm - 0.3413193965 * s);
  const bl = clamp(-0.0041960863 * l - 0.7034186147 * mm + 1.707614701 * s);
  return 0.2126 * r + 0.7152 * g + 0.0722 * bl;
}
const ratio = (x, y) => (Math.max(x, y) + 0.05) / (Math.min(x, y) + 0.05);

/** [foreground, background, minimum ratio]. 4.5 for text, 3 for UI boundaries. */
const PAIRS = [
  ...['fg', 'fg-muted', 'fg-subtle', 'fg-link'].flatMap((f) =>
    ['surface', 'bg', 'surface-muted', 'surface-hover'].map((b) => [f, b, 4.5]),
  ),
  ['fg', 'surface-selected', 4.5],
  ['fg', 'surface-sunken', 4.5],
  ['fg-muted', 'surface-sunken', 4.5],
  ['fg-inverse', 'surface-inverse', 4.5],
  ['border-input', 'surface', 3],
  ['ring', 'surface', 3],
  ['ring', 'bg', 3],
  ...['primary', 'critical', 'success', 'warning', 'info'].flatMap((t) => [
    [`${t}-fg`, t, 4.5],
    [`${t}-fg`, `${t}-hover`, 4.5],
    [`${t}-fg`, `${t}-active`, 4.5],
    [`${t}-subtle-fg`, `${t}-subtle`, 4.5],
    [`${t}-subtle-fg`, 'surface', 4.5],
  ]),
];
const contrastFailures = [];
const contrastReport = {};
for (const t of Object.keys(themes)) {
  contrastReport[t] = [];
  for (const [f, b, min] of PAIRS) {
    const lf = luminance(literal(t, f));
    const lb = luminance(literal(t, b));
    if (lf == null || lb == null) continue;
    const r = ratio(lf, lb);
    contrastReport[t].push({ fg: f, bg: b, ratio: +r.toFixed(2), min });
    if (r < min) contrastFailures.push(`${t}: ${f} on ${b} = ${r.toFixed(2)} (needs ${min})`);
  }
}
if (contrastFailures.length) {
  console.error(`Contrast check failed:\n  ${contrastFailures.join('\n  ')}`);
  process.exit(1);
}

// ── scales ─────────────────────────────────────────────────────────────────
const scaleVars = [];
for (const [scale, values] of Object.entries(scales)) {
  for (const [name, v] of Object.entries(values)) {
    if (Array.isArray(v)) {
      scaleVars.push([`--a-${scale}-${key(name)}`, v[0]]);
      scaleVars.push([`--a-${scale}-${key(name)}-line-height`, v[1]]);
    } else scaleVars.push([`--a-${scale}-${key(name)}`, v]);
  }
}

const block = (selector, vars) => `${selector} {\n${vars.map(([n, v]) => `  ${n}: ${v};`).join('\n')}\n}\n`;

let tokensCss = HEADER;
tokensCss += block(':root', [...paletteVars, ...scaleVars]);
for (const t of themeNames) {
  const selector = t === 'light' ? `:root,\n[data-theme='light']` : `[data-theme='${t}']`;
  const vars = colorNames.map((c) => [`--a-color-${c}`, resolveColor(themes[t][c], `${t}.${c}`)]);
  tokensCss += '\n' + block(selector, [[`color-scheme`, t], ...vars]);
}
writeFileSync(out('src/styles/tokens.generated.css'), tokensCss);

// ── Tailwind theme ─────────────────────────────────────────────────────────
const theme = [];
const ns = (title, reset, entries) => {
  theme.push(`  /* ${title} */`);
  if (reset) theme.push(`  ${reset}: initial;`);
  for (const [n, v] of entries) theme.push(`  ${n}: ${v};`);
};
ns('color', '--color-*', [
  ['--color-transparent', 'transparent'],
  ['--color-current', 'currentColor'],
  ...colorNames.map((c) => [`--color-${c}`, `var(--a-color-${c})`]),
]);
ns('spacing — 4px unit, so p-4 = 1rem', '--spacing-*', [
  ['--spacing', 'var(--a-space-1)'],
  ...Object.keys(scales.control).map((c) => [`--spacing-control-${c}`, `var(--a-control-${c})`]),
]);
ns('radius', '--radius-*', Object.keys(scales.radius).map((r) => [`--radius-${r}`, `var(--a-radius-${r})`]));
ns('font family', '--font-*', Object.keys(scales.font).map((f) => [`--font-${f}`, `var(--a-font-${f})`]));
ns(
  'type scale',
  '--text-*',
  Object.keys(scales.text).flatMap((s) => [
    [`--text-${s}`, `var(--a-text-${s})`],
    [`--text-${s}--line-height`, `var(--a-text-${s}-line-height)`],
  ]),
);
ns('font weight', '--font-weight-*', Object.keys(scales['font-weight']).map((w) => [`--font-weight-${w}`, `var(--a-font-weight-${w})`]));
ns('tracking', '--tracking-*', Object.keys(scales.tracking).map((t) => [`--tracking-${t}`, `var(--a-tracking-${t})`]));
ns('shadow', '--shadow-*', Object.keys(scales.shadow).map((s) => [`--shadow-${s}`, `var(--a-shadow-${s})`]));
ns('easing', '--ease-*', Object.keys(scales.ease).map((e) => [`--ease-${e}`, `var(--a-ease-${e})`]));
// Breakpoints are read at build time by Tailwind, so they carry literal values.
ns('breakpoint', '--breakpoint-*', Object.entries(scales.breakpoint).map(([b, v]) => [`--breakpoint-${b}`, v]));

const entryCount = theme.filter((l) => l.startsWith('  --') && !l.includes(': initial')).length;
const namespaceCount = theme.filter((l) => l.startsWith('  /*')).length;
writeFileSync(out('src/styles/theme.generated.css'), `${HEADER}@theme inline {\n${theme.join('\n')}\n}\n`);

// ── TypeScript ─────────────────────────────────────────────────────────────
const ts = [
  HEADER,
  `export const colorTokens = ${JSON.stringify(colorNames)} as const;`,
  'export type ColorToken = (typeof colorTokens)[number];',
  '',
  `export const toneNames = ['primary', 'critical', 'success', 'warning', 'info'] as const;`,
  'export type Tone = (typeof toneNames)[number];',
  '',
  `export const palette = ${JSON.stringify(palette, null, 2)} as const;`,
  '',
  `export const themes = ${JSON.stringify(themes, null, 2)} as const;`,
  '',
  `export const scales = ${JSON.stringify(scales, null, 2)} as const;`,
  '',
  `export const contrast = ${JSON.stringify(contrastReport)} as const;`,
  '',
  'export type SpaceToken = keyof typeof scales.space;',
  'export type RadiusToken = keyof typeof scales.radius;',
  'export type TextToken = keyof typeof scales.text;',
  'export type ShadowToken = keyof typeof scales.shadow;',
  '',
].join('\n');
writeFileSync(out('src/lib/tokens.generated.ts'), ts);

console.log(`contrast ok: ${PAIRS.length} pairs × ${Object.keys(themes).length} themes meet WCAG AA`);
console.log(
  `${paletteVars.length} palette + ${scaleVars.length} scale + ${colorNames.length}×${themeNames.length} semantic tokens ` +
    `-> ${entryCount} Tailwind theme entries across ${namespaceCount} namespaces`,
);
