#!/usr/bin/env node
/**
 * Fills gaps: for every manifest entry at `depth: 'first-pass'` whose files
 * are missing, writes a first-pass component and story from its archetype.
 *
 *   node packages/ui/scripts/generate.mjs            # write missing files
 *   node packages/ui/scripts/generate.mjs --dry-run  # list what it would write
 *
 * It never overwrites an existing file, and never writes anything for a
 * `depth: 'full'` component: an archetype story's args would describe the
 * archetype, not the real props, and would fail to typecheck.
 *
 * A first-pass component has real tokens, a sensible prop surface, semantic
 * HTML and focus handling — but minimal behaviour. It says so in its
 * docblock and its story. Promote it by rewriting it by hand and setting
 * `depth: 'full'` in the manifest.
 */
import { existsSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { components } from './manifest.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const dir = join(here, '../src/components');
const dryRun = process.argv.includes('--dry-run');

const pascal = (name) => name.replace(/[^A-Za-z0-9]/g, '');

const ARCHETYPES = {
  /** A bordered container with a heading and content. */
  surface: (c) => ({
    element: 'section',
    props: `  /** Heading shown at the top. */\n  title?: ReactNode;\n  children?: ReactNode;`,
    body: `
    <section className={cn('flex flex-col gap-3 rounded-lg border border-border bg-surface p-4 shadow-xs', className)} {...props}>
      {title ? <h2 className="text-lg font-semibold text-fg">{title}</h2> : null}
      {children}
    </section>`,
    args: `{ title: '${c.name}', children: 'Content' }`,
  }),
  /** A focusable form control with a label. */
  control: (c) => ({
    element: 'input',
    props: `  /** Visible label; also the accessible name. */\n  label: string;\n  /** Marks the value invalid and shows the message. */\n  error?: string;`,
    body: `
    <label className="flex flex-col gap-1 text-md font-medium text-fg">
      {label}
      <input
        aria-invalid={error ? true : undefined}
        className={cn(
          'h-control-md rounded-md border border-border-input bg-surface px-3 font-regular text-fg',
          'focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-ring',
          error && 'border-critical',
          className,
        )}
        {...props}
      />
      {error ? <span className="text-sm font-regular text-critical-subtle-fg">{error}</span> : null}
    </label>`,
    args: `{ label: '${c.name}' }`,
  }),
  /** Read-only display of content. */
  display: (c) => ({
    element: 'div',
    props: `  children?: ReactNode;`,
    body: `
    <div className={cn('text-md text-fg', className)} {...props}>
      {children}
    </div>`,
    args: `{ children: '${c.name}' }`,
  }),
};

function componentSource(c) {
  const a = ARCHETYPES[c.archetype](c);
  const Name = pascal(c.name);
  const destructure = { surface: 'title, children, className', control: 'label, error, className', display: 'children, className' }[c.archetype];
  const omit = c.archetype === 'surface' ? `, 'title'` : '';
  return `import type { ComponentPropsWithRef${c.archetype === 'control' ? '' : ', ReactNode'} } from 'react';
import { cn } from '../lib/cn';

export interface ${Name}Props extends Omit<ComponentPropsWithRef<'${a.element}'>, 'children'${omit}> {
${a.props}
}

/**
 * ${c.name}.
 *
 * **First pass** — correct tokens, prop surface and semantics, but minimal
 * behaviour: ${c.gap ?? 'interaction beyond the basics is not implemented yet'}.
 * Generated by scripts/generate.mjs; rewrite by hand and mark \`depth: 'full'\`
 * in scripts/manifest.mjs when it is ported.
 */
export function ${Name}({ ${destructure}, ...props }: ${Name}Props) {
  return (${a.body}
  );
}
`;
}

function storySource(c) {
  const a = ARCHETYPES[c.archetype](c);
  const Name = pascal(c.name);
  return `import type { Meta, StoryObj } from '@storybook/react-vite';
import { ${Name} } from './${c.file}';

const meta = {
  title: '${c.level}/${c.name}',
  component: ${Name},
  args: ${a.args},
  parameters: {
    docs: {
      description: {
        component:
          '**First pass** — styled placeholder with the intended API; ${(c.gap ?? 'behaviour is minimal').replace(/'/g, "\\'")}. ${(c.purpose ?? '').replace(/'/g, "\\'")}',
      },
    },
  },
} satisfies Meta<typeof ${Name}>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {};
`;
}

let written = 0;
for (const c of components) {
  if (c.depth === 'full') continue;
  if (!ARCHETYPES[c.archetype]) {
    console.error(`${c.name}: unknown archetype "${c.archetype}"`);
    process.exitCode = 1;
    continue;
  }
  for (const [path, source] of [
    [join(dir, `${c.file}.tsx`), componentSource],
    [join(dir, `${c.file}.stories.tsx`), storySource],
  ]) {
    if (existsSync(path)) continue;
    written++;
    if (dryRun) console.log(`would write ${path}`);
    else writeFileSync(path, source(c));
  }
}
console.log(`${dryRun ? 'would write' : 'wrote'} ${written} file(s); existing files untouched`);
