#!/usr/bin/env node
/**
 * STATUS.md is generated from scripts/manifest.mjs, so it cannot lag.
 *
 *   node packages/ui/scripts/status.mjs          # rewrite STATUS.md
 *   node packages/ui/scripts/status.mjs --check  # fail if stale or inconsistent
 *
 * --check fails when: STATUS.md differs from what would be generated; a
 * manifest entry's component or story file is missing; a component file in
 * src/components has no manifest entry; a first-pass component's docblock
 * doesn't say "First pass".
 */
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { LEVELS, components } from './manifest.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const dir = join(root, 'src/components');
const statusPath = join(root, 'STATUS.md');
const check = process.argv.includes('--check');

const problems = [];
const inManifest = new Set();
for (const c of components) {
  inManifest.add(c.file);
  for (const f of [`${c.file}.tsx`, `${c.file}.stories.tsx`]) {
    if (!existsSync(join(dir, f))) problems.push(`${c.name}: missing src/components/${f}`);
  }
  if (c.depth !== 'full' && existsSync(join(dir, `${c.file}.tsx`))) {
    if (!readFileSync(join(dir, `${c.file}.tsx`), 'utf8').includes('First pass')) {
      problems.push(`${c.name}: first-pass component must say "First pass" in its docblock`);
    }
  }
}
for (const f of readdirSync(dir)) {
  if (!f.endsWith('.tsx') || f.endsWith('.stories.tsx') || f.endsWith('.test.tsx')) continue;
  const file = f.replace(/\.tsx$/, '');
  if (!inManifest.has(file) && !components.some((c) => c.parts?.includes(file))) {
    problems.push(`src/components/${f} has no manifest entry`);
  }
}

const full = components.filter((c) => c.depth === 'full');
const first = components.filter((c) => c.depth !== 'full');
let md = `<!-- GENERATED by scripts/status.mjs from scripts/manifest.mjs. Do not edit. -->\n\n`;
md += `# Component status\n\n`;
md += `**${components.length} components** — ${full.length} full, ${first.length} first pass.\n\n`;
md += `- **full** — hand-written, behaviour complete, every applicable interface state has a story, verified in Storybook.\n`;
md += `- **first pass** — right tokens, prop surface and semantics; behaviour minimal. Placeholders with the intended API.\n\n`;
for (const level of LEVELS) {
  const list = components.filter((c) => c.level === level);
  if (list.length === 0) continue;
  md += `## ${level}\n\n| Component | Depth | Behaviour from | File | Notes |\n|---|---|---|---|---|\n`;
  for (const c of list) {
    md += `| ${c.name} | ${c.depth === 'full' ? 'full' : '**first pass**'} | ${c.radix ? `Radix ${c.radix}` : '—'} | \`${c.file}.tsx\` | ${c.depth === 'full' ? c.notes ?? '' : `Missing: ${c.gap}`} |\n`;
  }
  md += '\n';
}

if (check) {
  if (!existsSync(statusPath) || readFileSync(statusPath, 'utf8') !== md) {
    problems.push('STATUS.md is stale — run `bun run --filter @repo/ui status`');
  }
  if (problems.length) {
    console.error(problems.map((p) => `✗ ${p}`).join('\n'));
    process.exit(1);
  }
  console.log(`status ok: ${full.length} full, ${first.length} first pass`);
} else {
  writeFileSync(statusPath, md);
  if (problems.length) console.warn(problems.map((p) => `! ${p}`).join('\n'));
  console.log(`STATUS.md written: ${full.length} full, ${first.length} first pass`);
}
