import type { ComponentPropsWithRef } from 'react';
import { cn } from '../lib/cn';

export interface RangeSliderProps extends Omit<ComponentPropsWithRef<'input'>, 'children'> {
  /** Visible label; also the accessible name. */
  label: string;
  /** Marks the value invalid and shows the message. */
  error?: string;
}

/**
 * RangeSlider.
 *
 * **First pass** — correct tokens, prop surface and semantics, but minimal
 * behaviour: no slider track, thumbs, dual range or keyboard stepping.
 * Generated by scripts/generate.mjs; rewrite by hand and mark `depth: 'full'`
 * in scripts/manifest.mjs when it is ported.
 */
export function RangeSlider({ label, error, className, ...props }: RangeSliderProps) {
  return (
    <label className="flex flex-col gap-1 text-md font-medium text-fg">
      {label}
      <input
        aria-invalid={error ? true : undefined}
        className={cn(
          'h-control-md rounded-md border border-border-input bg-surface px-3 font-regular text-fg',
          'focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-ring',
          error && 'border-critical',
          className,
        )}
        {...props}
      />
      {error ? <span className="text-sm font-regular text-critical-subtle-fg">{error}</span> : null}
    </label>
  );
}
